//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAdressBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdressBook
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string EMail { get; set; }
        public string Subdivision { get; set; }
        public string StatePosition { get; set; }
    }
}
